require('dotenv').config()
const { getSheets } = require('../config/google')
const { SPREADSHEET_ID, SHEET_LEADS } = require('../config/sheets')
const { leadToRow } = require('../utils/formatters')

const SEED_LEADS = [
  { id:1, name:'Juan Pérez', company:'TechStart Colombia', email:'juan@techstart.co', phone:'+573001234567', country:'🇨🇴 Colombia', sector:'Tecnología', score:92, level:'A', stage:'01', valueUSD:45000, probability:85, painType:'Estratégico', projectStage:'Idea', source:'Web', assignee:'Carlos Suárez', flowType:'', tier:'', reportIA:false, blueprintDone:false, ivcRS:0, ivcPP:0, ivcRT:0, ivcES:0, ivcScore:'', slaActive:false, slaStartTime:'', notes:'', createdAt:'2026-05-12', updatedAt:'2026-05-12', entryType:'automatic', nextAction:'Activar análisis IA', nextActionDate:'2026-05-13', nextActionAssignee:'Carlos Suárez', loomUrl:'', deliverableUrl:'', driveFolderId:'' },
  { id:2, name:'María González', company:'AgroInvest SAS', email:'maria@agroinvest.co', phone:'+573109876543', country:'🇨🇴 Colombia', sector:'Agrícola', score:78, level:'B', stage:'04', valueUSD:25000, probability:70, painType:'Financiero', projectStage:'MVP', source:'LinkedIn', assignee:'Eusimary Contreras', flowType:'', tier:'', reportIA:true, blueprintDone:false, ivcRS:0, ivcPP:0, ivcRT:0, ivcES:0, ivcScore:'', slaActive:false, slaStartTime:'', notes:'Contactar por WhatsApp primero', createdAt:'2026-04-28', updatedAt:'2026-05-10', entryType:'automatic', nextAction:'Agendar Blueprint Session', nextActionDate:'2026-05-14', nextActionAssignee:'Eusimary Contreras', loomUrl:'', deliverableUrl:'', driveFolderId:'' },
  { id:3, name:'Roberto Silva', company:'HealthTech Ltda', email:'rsilva@healthtech.br', phone:'+5511987654321', country:'🇧🇷 Brasil', sector:'Salud', score:95, level:'A', stage:'07', valueUSD:85000, probability:90, painType:'Operativo', projectStage:'En Operación', source:'Referido', assignee:'Carlos Suárez', flowType:'Flujo 1', tier:'Premium', reportIA:true, blueprintDone:true, ivcRS:9, ivcPP:0.85, ivcRT:3, ivcES:2, ivcScore:1.28, slaActive:true, slaStartTime:new Date(Date.now()-18*3600*1000).toISOString(), notes:'Cliente Premium — sector salud digital.', createdAt:'2026-04-20', updatedAt:'2026-05-13', entryType:'automatic', nextAction:'Completar investigación Premium', nextActionDate:'2026-05-14', nextActionAssignee:'Carlos Suárez', loomUrl:'', deliverableUrl:'', driveFolderId:'' },
  { id:4, name:'Andrea Torres', company:'MinExplore LLC', email:'atorres@minexplore.mx', phone:'+525512345678', country:'🇲🇽 México', sector:'Minería', score:88, level:'A', stage:'09', valueUSD:120000, probability:75, painType:'Estructural', projectStage:'Expansión', source:'Web', assignee:'Carlos Suárez', flowType:'Flujo 1', tier:'Premium', reportIA:true, blueprintDone:true, ivcRS:10, ivcPP:0.8, ivcRT:4, ivcES:3, ivcScore:0.67, slaActive:false, slaStartTime:'', notes:'Proyecto de expansión minera.', createdAt:'2026-04-15', updatedAt:'2026-05-11', entryType:'automatic', nextAction:'Segunda reunión propuesta', nextActionDate:'2026-05-15', nextActionAssignee:'Carlos Suárez', loomUrl:'https://loom.com/share/example_1', deliverableUrl:'https://drive.google.com/file/example_1', driveFolderId:'' },
  { id:5, name:'Carlos Mendez', company:'FinGroup SA', email:'cmendez@fingroup.com', phone:'+584121234567', country:'🇻🇪 Venezuela', sector:'Finanzas', score:55, level:'C', stage:'17', valueUSD:8000, probability:20, painType:'Financiero', projectStage:'Idea', source:'WhatsApp', assignee:'Eusimary Contreras', flowType:'', tier:'', reportIA:true, blueprintDone:false, ivcRS:0, ivcPP:0, ivcRT:0, ivcES:0, ivcScore:'', slaActive:false, slaStartTime:'', notes:'En nurturing. Recursos limitados.', createdAt:'2026-03-10', updatedAt:'2026-05-01', entryType:'automatic', nextAction:'Enviar email nurturing #3', nextActionDate:'2026-05-20', nextActionAssignee:'Sistema', loomUrl:'', deliverableUrl:'', driveFolderId:'' },
  { id:6, name:'Sofía Ruiz', company:'EduTech Pro', email:'sruiz@edutechpro.es', phone:'+34612345678', country:'🇪🇸 España', sector:'Tecnología', score:71, level:'B', stage:'10', valueUSD:32000, probability:65, painType:'Estratégico', projectStage:'MVP', source:'LinkedIn', assignee:'Carlos Suárez', flowType:'Flujo 1', tier:'Pro', reportIA:true, blueprintDone:true, ivcRS:8, ivcPP:0.7, ivcRT:3, ivcES:4, ivcScore:0.47, slaActive:false, slaStartTime:'', notes:'Reunión directivos el 20/05.', createdAt:'2026-04-25', updatedAt:'2026-05-12', entryType:'automatic', nextAction:'Preparar propuesta Pro', nextActionDate:'2026-05-19', nextActionAssignee:'Carlos Suárez', loomUrl:'https://loom.com/share/example_2', deliverableUrl:'https://drive.google.com/file/example_2', driveFolderId:'' },
  { id:7, name:'Diego Morales', company:'Constructora BM', email:'dmorales@bm.co', phone:'+573151234567', country:'🇨🇴 Colombia', sector:'Construcción', score:83, level:'B', stage:'13', valueUSD:65000, probability:80, painType:'Operativo', projectStage:'En Operación', source:'Referido', assignee:'Carlos Suárez', flowType:'Flujo 1', tier:'Pro', reportIA:true, blueprintDone:true, ivcRS:8, ivcPP:0.75, ivcRT:3, ivcES:3, ivcScore:0.67, slaActive:false, slaStartTime:'', notes:'Decisor = Gerente General. Cierre el 22/05.', createdAt:'2026-04-10', updatedAt:'2026-05-13', entryType:'automatic', nextAction:'Reunión de cierre y firma', nextActionDate:'2026-05-22', nextActionAssignee:'Carlos Suárez', loomUrl:'', deliverableUrl:'', driveFolderId:'' },
  { id:8, name:'Isabel Vargas', company:'GreenEnergy SAS', email:'ivargas@greenenergy.co', phone:'+573001112233', country:'🇨🇴 Colombia', sector:'Energía', score:91, level:'A', stage:'03', valueUSD:55000, probability:60, painType:'Técnico', projectStage:'MVP', source:'Web', assignee:'Carlos Suárez', flowType:'', tier:'', reportIA:true, blueprintDone:false, ivcRS:0, ivcPP:0, ivcRT:0, ivcES:0, ivcScore:'', slaActive:false, slaStartTime:'', notes:'Reporte IA listo. Contactar hoy.', createdAt:'2026-05-08', updatedAt:'2026-05-13', entryType:'automatic', nextAction:'Contactar para Blueprint Session', nextActionDate:'2026-05-13', nextActionAssignee:'Carlos Suárez', loomUrl:'', deliverableUrl:'', driveFolderId:'' },
  { id:9, name:'Fernando Castillo', company:'LogistiPro LATAM', email:'fcastillo@logistipro.pe', phone:'+51987654321', country:'🇵🇪 Perú', sector:'Logística', score:67, level:'B', stage:'06', valueUSD:18000, probability:55, painType:'Operativo', projectStage:'En Operación', source:'Evento', assignee:'Eusimary Contreras', flowType:'Flujo 2', tier:'', reportIA:true, blueprintDone:false, ivcRS:0, ivcPP:0, ivcRT:0, ivcES:0, ivcScore:'', slaActive:false, slaStartTime:'', notes:'Sesión en progreso — Flujo 2 gratuito.', createdAt:'2026-05-05', updatedAt:'2026-05-13', entryType:'automatic', nextAction:'Completar 21 preguntas IVC', nextActionDate:'2026-05-13', nextActionAssignee:'Eusimary Contreras', loomUrl:'', deliverableUrl:'', driveFolderId:'' },
  { id:10, name:'Camila Pinto', company:'Inmobiliaria Alpha', email:'cpinto@alpha.cl', phone:'+56912345678', country:'🇨🇱 Chile', sector:'Inmobiliario', score:35, level:'D', stage:'18', valueUSD:0, probability:0, painType:'Financiero', projectStage:'Idea', source:'LinkedIn', assignee:'Eusimary Contreras', flowType:'', tier:'', reportIA:true, blueprintDone:false, ivcRS:0, ivcPP:0, ivcRT:0, ivcES:0, ivcScore:'', slaActive:false, slaStartTime:'', notes:'Closed Lost — Sin recursos financieros.', createdAt:'2026-03-25', updatedAt:'2026-04-10', entryType:'automatic', nextAction:'Archivar', nextActionDate:'', nextActionAssignee:'Sistema', loomUrl:'', deliverableUrl:'', driveFolderId:'' },
]

async function seed() {
  const sheets = await getSheets()
  const rows = SEED_LEADS.map(l => leadToRow({
    closedLostReason: '', closedLostCategory: '', recontactDate: null,
    reportContent: null, leadCode: null,
    ...l,
  }))

  await sheets.spreadsheets.values.append({
    spreadsheetId: SPREADSHEET_ID,
    range: `${SHEET_LEADS}!A2`,
    valueInputOption: 'RAW',
    requestBody: { values: rows }
  })

  console.log(`✅ ${rows.length} leads importados a Google Sheets`)
}

seed().catch(e => { console.error('❌', e.message); process.exit(1) })
